name: vst
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=3.0.2
  - werkzeug=3.0.1
  - python-dateutil=2.8.2
  - click=8.1.7
  - itsdangerous=2.1.2
  - jinja2=3.1.3
  - markupsafe=2.1.5
  - pip
  - pip:
    - uuid==1.30